name: msa
description: "Una aplicación de Flutter para el seguimiento de la salud y el bienestar."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # === CORE Y UTILIDADES ===
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

  # === FIREBASE ===
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.4
  firebase_messaging: ^14.9.4
  firebase_app_check: ^0.2.2+1
  google_sign_in: ^6.2.1

  # === UI & UX ===
  flutter_colorpicker: ^1.1.0
  fl_chart: ^0.68.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0

  # === NOTIFICACIONES ===
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3

  # === OTROS ===
  tuple: ^2.0.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  android_gravity: center
  ios_content_mode: center
